# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b0c74401846be86a5df7bfbbf4bb4daf41e87772e224f89d8748e12288ed65f43cb2a45b30d34afd27e7acb205698de3f34d831c3a4cdc97676fa59e253e310c

test:
  secret_key_base: 576c848da656a5f10d91c2a04d48cbcbe89bebf79bd8a15f3132117d03cb155a77f659b338fe251ff2da9a61dad1cd43182b02852d8bae936cc11271a5108ab6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
